### ISSUE TITLE
Some Documentation Suggestions

### ISSUE THREAD

**Issue by mayermelhem** [ccaprani/pycba#3]
Fantastic package. Please find below some first comments on the documentation upon my early trials of the program: 

1. Installation should say
```pip install -e .```
and not 
```pip install . -e```

2. `eType` seen in the tutorials is not made clear that it is element type (or `eletype` kwarg). Suggest under beam configuration  including the `eletype` kwarg in the Element Type Header in brackets, to be analogues to other headers that present their kwargs.

3. It is not abundantly clear the default vehicle direction for moving loads (my guess from tutorial plot was left to right end support, first axle followed by second axle), nor if a reverse direction can be explored.

On 3, some functions found [here](https://github.com/ccaprani/PyBridge/blob/master/pybridge/load_analysis/moving_load.py), could be useful to integrate in `PyCBA`

**Comment by ccaprani** [comment]
Thanks @mayermelhem ; addressed in [a010fd4](https://github.com/ccaprani/pycba/commit/a010fd4db2bb9737789f7f0a5f3cf1df6eada2ab); added a basic reverse vehicle feature too.

Those referenced functions are great - lots of good functionality that could be added here. I'd rather not take credit for moving them over - would you consider a PR?
