### ISSUE TITLE
How to use Pycba calculate deflection of  a cable-stayed bridge? 

### ISSUE THREAD

**Issue by kunyaoli** [ccaprani/pycba#54]
![图片](https://github.com/ccaprani/pycba/assets/39542806/0ea5436d-3da2-421c-8f76-10b20fad9851)

Hi, thanks for your work. I have a question about how to calculate deflection of  a cable-stayed bridge like the picture.

**Comment by AlexGriffiths526** [comment]
I think this could be done in a sense by just modelling the deck and applying spring supports to represent the cables. However, it would be better suited to a 2D analysis package as estimation of the spring stiffnesses will be quite challenging in itself.

**Comment by ccaprani** [comment]
Exactly @AlexGriffiths526 ; an equivalent spring stiffness taking into account the cable angle and prestressing is a good first approximation to the real (complex) behaviour. Something like this: https://www.researchgate.net/publication/264168489_Equivalent_stiffness_method_for_nonlinear_analysis_of_stay_cables
