### ISSUE TITLE
Envelope for moving vehicle + load pattern

### ISSUE THREAD

**Issue by Grefron** [ccaprani/pycba#56]
Hi!

First off, thanks for a nice package, i have been looking for this!

I am trying to use pycba for the quick predesign of a large number of bridges. For this, I need to obtain envelope results for a udl load (through load patterning) combined with a moving vehicle load. I have obtained the max/min values already, but would like to get the envelope plotted as well.

The way i think this should work is to generate envelopes for both the load pattern and than add (augment) it with the moving load envelope. However, I can't seem to get it to work.... Can you give me some pointers?

Thanks in advance!

Ronald

**Comment by ccaprani** [comment]
Hi @Grefron , thanks for the nice comments 😊

Augmenting the envelopes *should* work. Could you share an minimal (non)working example of what you're trying please?

**Comment by ccaprani** [comment]
Hi @Grefron : I added a short example of this use case:
https://ccaprani.github.io/pycba/notebooks/envelopes.html#Example-4:-Augmenting-Envelopes

**Comment by Grefron** [comment]
Hi @ccaprani, thanks for the example, it showed exactly what I needed and what i did wrong: I tried to augment an envelope with a beam result, which doesn't work, obviously.
