### ISSUE TITLE
scipy.integrate has no attribute cumtrapz

### ISSUE THREAD

**Issue by alexandergriffiths526** [ccaprani/pycba#99]
Hi Colin, 
Recently my pycba won't analyze. I get an error when running the "beam_analysis.analyze()" I think this is due to a change in syntax of scipy cumtrapz to cumulative_trapezoid.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.cumulative_trapezoid.html

In the pyproject.toml I can't see which version of scipy is the dependency so haven't tried to install an older version.

**Comment by ccaprani** [comment]
Thank you @alexandergriffiths526 ! The `cumtrapz` is used [here](https://github.com/ccaprani/pycba/blob/f109c7e2814cce7a46c844f9a84697f44486596e/src/pycba/results.py#L176) but this was renamed in [scipy version 1.6](https://docs.scipy.org/doc/scipy/release/1.6.0-notes.html). You're absolutely right in that we didn't pin a version of scipy [here](https://github.com/ccaprani/pycba/blob/f109c7e2814cce7a46c844f9a84697f44486596e/pyproject.toml#L33).

The immediate solution is to downgrade your scipy in teh same environment as pycba to v1.5.4 which is the latest compatible version: `pip install scipy==1.5.4`.

I'll change pycba to require scipy > 1.6.0 and change the relevant line of code to use the `cumulative_trapezoid` name.

Thanks!
